package com.drivique.api;
import java.util.UUID; import org.junit.jupiter.api.*; import org.springframework.beans.factory.annotation.Autowired; import org.springframework.boot.webmvc.test.autoconfigure.AutoConfigureMockMvc; import org.springframework.cache.CacheManager; import org.springframework.security.test.context.support.WithMockUser; import org.springframework.test.context.ActiveProfiles; import org.springframework.test.web.servlet.MockMvc;
import static org.springframework.test.web.servlet.request.MockMvcRequestBuilders.*; import static org.springframework.test.web.servlet.result.MockMvcResultMatchers.*;
@ActiveProfiles("dev") @AutoConfigureMockMvc class FleetCatalogIntegrationTests extends DatabaseHealthTestSupport {
 @Autowired MockMvc mvc; @Autowired CacheManager caches;
 @BeforeEach void reset(){jdbc.update("delete from fleet.vehicles");jdbc.update("delete from fleet.vehicle_statuses");jdbc.update("delete from fleet.fuel_types");jdbc.update("delete from fleet.transmission_types");jdbc.update("delete from fleet.vehicle_brands");for(String c: new String[]{"vehicleBrands","transmissionTypes","fuelTypes","reservableVehicleStatuses"})caches.getCache(c).clear();}
 @Test void publicCatalogsExposeActiveAndReservableValues() throws Exception { UUID b=UUID.randomUUID();jdbc.update("insert into fleet.vehicle_brands(id,name,is_active) values(?,?,true)",b,"Toyota");jdbc.update("insert into fleet.transmission_types(id,code,name,is_active) values(?,?,?,true)",UUID.randomUUID(),"AUTOMATIC","Automatic");jdbc.update("insert into fleet.fuel_types(id,code,name,is_active) values(?,?,?,true)",UUID.randomUUID(),"ELECTRIC","Electric");jdbc.update("insert into fleet.vehicle_statuses(id,code,name,allows_reservation,is_active) values(?,?,?,?,true)",UUID.randomUUID(),"AVAILABLE","Available",true);jdbc.update("insert into fleet.vehicle_statuses(id,code,name,allows_reservation,is_active) values(?,?,?,?,true)",UUID.randomUUID(),"RENTED","Rented",false);
  mvc.perform(get("/api/v1/vehicle-brands").contextPath("/api")).andExpect(status().isOk()).andExpect(jsonPath("$[0].name").value("Toyota")); mvc.perform(get("/api/v1/transmission-types").contextPath("/api")).andExpect(jsonPath("$[0].code").value("AUTOMATIC"));mvc.perform(get("/api/v1/fuel-types").contextPath("/api")).andExpect(jsonPath("$[0].code").value("ELECTRIC"));mvc.perform(get("/api/v1/vehicle-statuses").contextPath("/api")).andExpect(jsonPath("$.length()").value(1)).andExpect(jsonPath("$[0].allowsReservation").value(true)); }
 @Test @WithMockUser(roles="SUPER_ADMIN") void adminCreatesUpdatesAndRejectsDuplicateBrands() throws Exception {mvc.perform(post("/api/v1/vehicle-brands").contextPath("/api").contentType("application/json").content("{\"name\":\"Mazda\"}")).andExpect(status().isCreated());UUID id=jdbc.queryForObject("select id from fleet.vehicle_brands where name='Mazda'",UUID.class);mvc.perform(put("/api/v1/vehicle-brands/{id}",id).contextPath("/api").contentType("application/json").content("{\"name\":\"Mazda Motors\"}")).andExpect(status().isOk()).andExpect(jsonPath("$.name").value("Mazda Motors"));mvc.perform(post("/api/v1/vehicle-brands").contextPath("/api").contentType("application/json").content("{\"name\":\"Mazda Motors\"}")).andExpect(status().isConflict());}
 @Test void anonymousCannotManageBrands() throws Exception {mvc.perform(post("/api/v1/vehicle-brands").contextPath("/api").contentType("application/json").content("{\"name\":\"Kia\"}")).andExpect(status().isUnauthorized());}
}
