package com.drivique.api.service;
import com.drivique.api.dto.*; import com.drivique.api.exception.*; import com.drivique.api.model.*; import com.drivique.api.repository.*; import java.util.*; import org.springframework.cache.annotation.*; import org.springframework.dao.DataIntegrityViolationException; import org.springframework.stereotype.Service; import org.springframework.transaction.annotation.Transactional;
@Service public class FleetCatalogService {
 private final VehicleBrandRepository brands; private final TransmissionTypeRepository transmissions; private final FuelTypeRepository fuels; private final VehicleStatusRepository statuses;
 public FleetCatalogService(VehicleBrandRepository b,TransmissionTypeRepository t,FuelTypeRepository f,VehicleStatusRepository s){brands=b;transmissions=t;fuels=f;statuses=s;}
 @Transactional(readOnly=true) @Cacheable("vehicleBrands") public List<TechnicalCatalogResponseDTO> brands(){return brands.findByActiveTrueOrderByNameAsc().stream().map(this::brand).toList();}
 @Transactional(readOnly=true) @Cacheable("transmissionTypes") public List<TechnicalCatalogResponseDTO> transmissions(){return transmissions.findByActiveTrueOrderByCodeAsc().stream().map(x->new TechnicalCatalogResponseDTO(x.getId(),x.getCode(),x.getName(),x.isActive(),false)).toList();}
 @Transactional(readOnly=true) @Cacheable("fuelTypes") public List<TechnicalCatalogResponseDTO> fuels(){return fuels.findByActiveTrueOrderByCodeAsc().stream().map(x->new TechnicalCatalogResponseDTO(x.getId(),x.getCode(),x.getName(),x.isActive(),false)).toList();}
 @Transactional(readOnly=true) @Cacheable("reservableVehicleStatuses") public List<TechnicalCatalogResponseDTO> statuses(){return statuses.findByActiveTrueAndAllowsReservationTrueOrderByCodeAsc().stream().map(x->new TechnicalCatalogResponseDTO(x.getId(),x.getCode(),x.getName(),x.isActive(),x.allowsReservation())).toList();}
 @Transactional @CacheEvict(value="vehicleBrands",allEntries=true) public TechnicalCatalogResponseDTO create(VehicleBrandRequestDTO i){String n=i.name().strip();if(brands.existsByNameIgnoreCase(n))throw new ConflictException("Vehicle brand already exists");try{return brand(brands.saveAndFlush(new VehicleBrand(n)));}catch(DataIntegrityViolationException e){throw new ConflictException("Vehicle brand conflicts with database constraints");}}
 @Transactional @CacheEvict(value="vehicleBrands",allEntries=true) public TechnicalCatalogResponseDTO update(UUID id,VehicleBrandRequestDTO i){VehicleBrand b=brands.findById(id).orElseThrow(()->new ResourceNotFoundException("Vehicle brand not found"));String n=i.name().strip();if(brands.existsByNameIgnoreCaseAndIdNot(n,id))throw new ConflictException("Vehicle brand already exists");b.update(n);try{return brand(brands.saveAndFlush(b));}catch(DataIntegrityViolationException e){throw new ConflictException("Vehicle brand conflicts with database constraints");}}
 private TechnicalCatalogResponseDTO brand(VehicleBrand x){return new TechnicalCatalogResponseDTO(x.getId(),null,x.getName(),x.isActive(),false);}
}
