package com.drivique.api.service;
import com.drivique.api.dto.*; import com.drivique.api.exception.*; import com.drivique.api.model.*; import com.drivique.api.repository.*;
import java.math.*; import java.time.*; import java.time.temporal.ChronoUnit; import java.util.*;
import org.springframework.cache.annotation.Cacheable; import org.springframework.stereotype.Service; import org.springframework.transaction.annotation.Transactional;
@Service public class PromotionValidationService {
 private final PromotionRepository promotions; private final UserCouponUsageRepository usages; private final UserRepository users; private final VehicleRepository vehicles;
 public PromotionValidationService(PromotionRepository promotions,UserCouponUsageRepository usages,UserRepository users,VehicleRepository vehicles){this.promotions=promotions;this.usages=usages;this.users=users;this.vehicles=vehicles;}
 @Transactional(readOnly=true) public PromotionValidationResponseDTO validate(PromotionValidationRequestDTO input,String email){Promotion p=promotions.findByCodeIgnoreCase(input.code().strip()).orElseThrow(()->new ResourceNotFoundException("Promotion not found"));Vehicle vehicle=vehicles.findById(input.vehicleId()).orElseThrow(()->new ResourceNotFoundException("Vehicle not found"));if(!vehicle.getCategory().getId().equals(input.categoryId()))throw new IllegalArgumentException("Vehicle does not match category");if(!p.isActive()||Instant.now().isBefore(p.getStartsAt())||!Instant.now().isBefore(p.getEndsAt()))throw new ConflictException("Promotion is not active");long days=Math.max(1,ChronoUnit.DAYS.between(input.pickupDate(),input.returnDate()));if(input.returnDate().isBefore(input.pickupDate())||days<p.getMinimumRentalDays())throw new ConflictException("Promotion conditions are not met");if(p.getMaxUsesLimit()!=null&&p.getCurrentUsesCount()>=p.getMaxUsesLimit())throw new ConflictException("Promotion use limit reached");User user=users.findByEmailIgnoreCaseAndDeletedAtIsNull(email).orElseThrow(()->new ResourceNotFoundException("User not found"));if(usages.existsByPromotionAndUser(p,user))throw new ConflictException("Promotion already used by this user");BigDecimal base=vehicle.getDailyRate().multiply(BigDecimal.valueOf(days));BigDecimal amount="PERCENTAGE".equals(p.getDiscountType())?base.multiply(p.getDiscountValue()).divide(BigDecimal.valueOf(100),2,RoundingMode.HALF_UP):p.getDiscountValue().min(base);return new PromotionValidationResponseDTO(p.getId(),p.getCode(),p.getDiscountType(),p.getDiscountValue(),amount,base);}
 @Transactional(readOnly=true) @Cacheable("featuredPromotions") public List<FeaturedPromotionResponseDTO> featured(){Instant now=Instant.now();return promotions.findByActiveTrueAndOfferTypeAndStartsAtLessThanEqualAndEndsAtAfterOrderByEndsAtAsc("PROMOTION",now,now).stream().map(p->new FeaturedPromotionResponseDTO(p.getId(),p.getCode(),p.getDiscountType(),p.getDiscountValue(),p.getEndsAt())).toList();}
}
