package com.drivique.api.service;

import com.drivique.api.dto.*; import com.drivique.api.exception.*; import com.drivique.api.model.*; import com.drivique.api.repository.*; import com.fasterxml.jackson.databind.JsonNode; import java.math.*; import java.time.Instant; import java.util.Locale; import java.util.UUID; import org.springframework.beans.factory.annotation.Value; import org.springframework.security.access.AccessDeniedException; import org.springframework.stereotype.Service; import org.springframework.transaction.annotation.Transactional;

@Service
public class WompiPaymentService {
 private final RentalContractRepository contracts; private final PaymentRepository payments; private final PaymentMethodRepository methods; private final PaymentStatusRepository statuses; private final CurrencyRepository currencies; private final UserRepository users; private final UserSavedPaymentMethodRepository savedMethods; private final ReservationStatusRepository reservationStatuses; private final WompiSignatureService signatures; private final String publicKey,integritySecret,eventSecret,checkoutUrl;
 public WompiPaymentService(RentalContractRepository contracts,PaymentRepository payments,PaymentMethodRepository methods,PaymentStatusRepository statuses,CurrencyRepository currencies,UserRepository users,UserSavedPaymentMethodRepository savedMethods,ReservationStatusRepository reservationStatuses,WompiSignatureService signatures,@Value("${payments.wompi.public-key:}") String publicKey,@Value("${payments.wompi.integrity-secret:}") String integritySecret,@Value("${payments.wompi.event-secret:}") String eventSecret,@Value("${payments.wompi.checkout-url:https://checkout.wompi.co/p/}") String checkoutUrl){this.contracts=contracts;this.payments=payments;this.methods=methods;this.statuses=statuses;this.currencies=currencies;this.users=users;this.savedMethods=savedMethods;this.reservationStatuses=reservationStatuses;this.signatures=signatures;this.publicKey=publicKey;this.integritySecret=integritySecret;this.eventSecret=eventSecret;this.checkoutUrl=checkoutUrl;}
 @Transactional public WompiCheckoutResponseDTO initiate(WompiInitiatePaymentRequestDTO input,String email){ RentalContract contract=contracts.findById(input.contractId()).orElseThrow(()->new ResourceNotFoundException("Contrato no encontrado")); User user=currentUser(email); if(!contract.getCustomer().getId().equals(user.getId()))throw new ResourceNotFoundException("Contrato no encontrado"); if(publicKey.isBlank())throw new IllegalStateException("No está configurada la llave pública de Wompi."); PaymentMethod method=methods.findByCodeIgnoreCaseAndActiveTrue(input.paymentMethodCode()).orElseThrow(()->new ResourceNotFoundException("Método de pago no disponible")); PaymentStatus pending=statuses.findByCodeIgnoreCase("PENDING").orElseThrow(()->new ResourceNotFoundException("Estado PENDING no encontrado")); Currency currency=currencies.findByCodeIgnoreCaseAndActiveTrue("COP").orElseThrow(()->new ResourceNotFoundException("Moneda COP no encontrada")); String reference="PAY-"+UUID.randomUUID().toString().replace("-",""); BigDecimal amount=contract.getBaseAmount().add(contract.getSecurityDeposit()); payments.saveAndFlush(new Payment(contract,method,pending,reference,amount,currency)); long cents=amount.movePointRight(2).setScale(0,RoundingMode.UNNECESSARY).longValueExact(); return new WompiCheckoutResponseDTO(checkoutUrl,publicKey,"COP",cents,reference,signatures.integrity(reference,cents,"COP",integritySecret)); }
 @Transactional public void processWebhook(JsonNode event,String headerChecksum){if(!signatures.validWebhook(event,headerChecksum,eventSecret))throw new AccessDeniedException("Firma de webhook inválida."); JsonNode tx=event.path("data").path("transaction"); String reference=tx.path("reference").asText(); String statusCode=tx.path("status").asText().toUpperCase(Locale.ROOT); if(reference.isBlank()||!("APPROVED".equals(statusCode)||"DECLINED".equals(statusCode)))return; Payment payment=payments.findByGatewayProviderAndGatewayReference("WOMPI",reference).orElseThrow(()->new ResourceNotFoundException("Pago no encontrado")); if(payment.getStatus().getCode().equalsIgnoreCase(statusCode))return; payment.setStatus(statuses.findByCodeIgnoreCase(statusCode).orElseThrow(()->new ResourceNotFoundException("Estado de pago no encontrado"))); if("APPROVED".equals(statusCode)){payment.setPaidAt(Instant.now()); payment.getContract().getReservation().setStatus(reservationStatuses.findByCodeIgnoreCase("CONFIRMED").orElseThrow(()->new ResourceNotFoundException("Estado CONFIRMED no encontrado")));} }
 @Transactional public SavedPaymentMethodResponseDTO saveToken(SaveWompiPaymentMethodRequestDTO input,String email){if(input.paymentToken().trim().matches("\\d{13,19}"))throw new IllegalArgumentException("No se permite almacenar números de tarjeta."); if(savedMethods.existsByPaymentToken(input.paymentToken().trim()))throw new ConflictException("El método de pago ya está registrado."); UserSavedPaymentMethod saved=savedMethods.saveAndFlush(new UserSavedPaymentMethod(currentUser(email),input.paymentToken().trim(),input.cardBrand().trim(),input.lastFour(),input.expMonth(),input.expYear())); return new SavedPaymentMethodResponseDTO(saved.getId(),saved.getCardBrand(),saved.getLastFour(),saved.getExpMonth(),saved.getExpYear()); }
 private User currentUser(String email){return users.findByEmailIgnoreCaseAndDeletedAtIsNull(email).orElseThrow(()->new ResourceNotFoundException("Usuario no encontrado"));}
}
